backend:
  image:
    repository: "ghcr.io/freeman-trader/free-batch-backend"
    tag: "main"
    pullPolicy: Always
  runOnce: true

frontend:
  replicas: 1
  image:
    repository: "ghcr.io/freeman-trader/free-batch-frontend"
    tag: "main"
    pullPolicy: Always
  restartPolicy: Always
  containerPort: 8080
  flaskHost: "0.0.0.0"
  flaskDebug: false
  service:
    type: ClusterIP
    port: 80
    portName: http

mysql:
  host: "localhost"
  containerPort: 3306
  user: "root"
  name: "jobs"
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  restartPolicy: Always
  service:
    type: ClusterIP
    port: 3306
    portName: mysql

rabbitmq:
  host: "localhost"
  containerPort: 5672
  managementPort: 15672
  queue: "job-queue"
  image:
    repository: rabbitmq
    tag: "4.3.0-management-alpine"
    pullPolicy: IfNotPresent
  restartPolicy: Always
  service:
    type: ClusterIP
    amqpPort: 5672
    managementPort: 15672
    amqpPortName: amqp
    managementPortName: management

secret:
  dbPassword: "Test123"

ingress:
  className: "nginx"
  hosts: 
    - host: "test.local"
      paths:
      - path: /
        pathType: Prefix
  