apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "free-batch.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "free-batch.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: {{ include "free-batch.name" . }}-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "free-batch.fullname" . }}-secret
            - configMapRef:
                name: {{ include "free-batch.fullname" . }}-config
      restartPolicy: Never
