apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: {{ include "free-batch.fullname" . }}-backend-scaler
  namespace: {{ .Release.Namespace }}
spec:
  jobTargetRef:
    template:
      spec:
        nodeSelector:
          kubernetes.io/os: linux
        containers:
          - name: backend
            image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
            envFrom:
              - secretRef:
                  name: {{ include "free-batch.fullname" . }}-secret
              - configMapRef:
                  name: {{ include "free-batch.fullname" . }}-config
        restartPolicy: Never
  
  pollingInterval: {{ .Values.backend.pollingInterval }}
  successfulJobsHistoryLimit: {{ .Values.backend.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.backend.failedJobsHistoryLimit }}
  maxReplicaCount: {{ .Values.backend.maxReplicaCount }}

  triggers:
    - type: rabbitmq
      metadata:
        queueName: {{ .Values.rabbitmq.queue }}
        mode: {{ .Values.backend.triggers.mode }}
        value: {{ .Values.backend.triggers.value | quote }}
        host: amqp://{{ .Values.rabbitmq.auth.user }}:{{ .Values.rabbitmq.auth.password }}@{{ include "free-batch.fullname" . }}-rabbitmq.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.rabbitmq.service.amqpPort }}/