apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "free-batch.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "free-batch.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.mysql.host }}
  DB_PORT: {{ .Values.mysql.port | quote }}
  DB_USER: {{ .Values.mysql.user }}
  DB_NAME: {{ .Values.mysql.name }}

  RABBITMQ_HOST: {{ .Values.rabbitmq.host }}
  RABBITMQ_PORT: {{ .Values.rabbitmq.port | quote }}
  RABBITMQ_QUEUE: {{ .Values.rabbitmq.queue }}

  RUN_ONCE: {{ .Values.backend.runOnce | quote }}

  FLASK_HOST: {{ .Values.frontend.flaskHost }}
  FLASK_PORT: {{ .Values.frontend.flaskPort | quote }}
  FLASK_DEBUG: {{ .Values.frontend.flaskDebug | quote }}
