apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "free-batch.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "free-batch.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ include "free-batch.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "free-batch.name" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
              name: http
          envFrom:
            - secretRef:
                name: {{ include "free-batch.fullname" . }}-secret
            - configMapRef:
                name: {{ include "free-batch.fullname" . }}-config
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
