apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "free-batch.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "free-batch.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ include "free-batch.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "free-batch.name" . }}-frontend
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: {{ .Values.frontend.restartPolicy }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
              name: http
          envFrom:
            - secretRef:
                name: {{ include "free-batch.fullname" . }}-secret
            - configMapRef:
                name: {{ include "free-batch.fullname" . }}-config

