apiVersion: v1
kind: Service
metadata:
  name: {{ include "free-batch.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "free-batch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.containerPort }}
      protocol: TCP
      name: {{ .Values.frontend.service.portName }}
  selector:
    app: {{ include "free-batch.name" . }}-frontend