apiVersion: v1
kind: Service
metadata:
  name: {{ include "free-batch.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "free-batch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "free-batch.name" . }}-frontend
