apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "free-batch.fullname" . }}-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "free-batch.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "free-batch.fullname" . }}-mysql
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "free-batch.name" . }}-mysql
  template:
    metadata:
      labels:
        app: {{ include "free-batch.name" . }}-mysql
    spec:
      restartPolicy: {{ .Values.mysql.restartPolicy }}
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.mysql.containerPort }}
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "free-batch.fullname" . }}-secret
                  key: DB_PASSWORD
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.name }}
          volumeMounts:
            - name: {{ .Values.mysql.volume.name }}
              mountPath: {{ .Values.mysql.volume.mountPath }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.mysql.volume.name }}
      spec:
        accessModes: {{ .Values.mysql.volume.accessModes | toYaml | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.mysql.volume.storage }}
