apiVersion: v1
kind: Service
metadata:
  name: {{ include "free-batch.fullname" . }}-rabbitmq
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "free-batch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.rabbitmq.service.type }}
  ports:
    - port: {{ .Values.rabbitmq.service.amqpPort }}
      targetPort: {{ .Values.rabbitmq.containerPort }}
      protocol: TCP
      name: {{ .Values.rabbitmq.service.amqpPortName }}
    - port: {{ .Values.rabbitmq.service.managementPort }}
      targetPort: {{ .Values.rabbitmq.managementPort }}
      protocol: TCP
      name: {{ .Values.rabbitmq.service.managementPortName }}
  selector:
    app: {{ include "free-batch.name" . }}-rabbitmq